customers:
  allow-get-customers: true

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: root
    password: Mamaitata1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "info,health,refresh,metrics,mappings"

server:
  port: 8887
