

accounts:
  allow-get-accounts: true
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9999,localhost:9998
#
#feign:
#  hystrix:
#    enabled: false

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: root
    password: Mamaitata1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    enable: false



management:
  endpoints:
    web:
      exposure:
        include: "*"
#
#server:
#  port: 7777
