#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    enable: true